# Generated by Django 5.2.9 on 2025-12-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=13)),
                ('birthday', models.DateField()),
                ('department', models.CharField(max_length=50)),
                ('student_number', models.CharField(max_length=7)),
                ('grade', models.CharField(max_length=20)),
                ('method', models.CharField(choices=[('OFFLINE', '대면'), ('ONLINE', '비대면')], max_length=20)),
                ('part', models.CharField(choices=[('PM_DESIGN', '기획·디자인'), ('FRONTEND', '프론트엔드'), ('BACKEND', '백엔드')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', '심사중'), ('APPROVED', '합격'), ('REJECTED', '불합격')], default='PENDING', max_length=10)),
                ('application_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_url', models.URLField()),
                ('time', models.DateTimeField()),
                ('question_1', models.TextField(max_length=500)),
                ('question_2', models.TextField(max_length=500)),
                ('question_3', models.TextField(max_length=500)),
                ('question_4', models.TextField(max_length=500)),
                ('question_5', models.TextField(max_length=500)),
            ],
        ),
    ]
