# Generated by Django 5.2.9 on 2025-12-29 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentSchedule',
            fields=[
                ('year', models.PositiveSmallIntegerField(help_text='모집 연도', primary_key=True, serialize=False)),
                ('application_start', models.DateTimeField(help_text='서류 지원 기간 시작')),
                ('application_end', models.DateTimeField(help_text='서류 지원 기간 종료')),
                ('application_result_start', models.DateTimeField(help_text='서류 합격자 발표 시작')),
                ('interview_start', models.DateTimeField(help_text='면접 기간 시작')),
                ('interview_end', models.DateTimeField(help_text='면접 기간 종료')),
                ('interview_result_start', models.DateTimeField(help_text='최종 합격자 발표 시작')),
                ('interview_result_end', models.DateTimeField(help_text='최종 합격자 발표 종료')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='면접 시작 일시 (end와 같은 날)')),
                ('end', models.DateTimeField(help_text='면접 종료 일시 (start와 같은 날)')),
                ('interview_method', models.CharField(choices=[('OFFLINE', '대면'), ('ONLINE', '비대면')], help_text='면접 방식', max_length=7)),
                ('recruitment_schedule', models.ForeignKey(help_text='특정 연도의 모집 일정', on_delete=django.db.models.deletion.CASCADE, related_name='interview_schedules', to='managers.recruitmentschedule')),
            ],
        ),
    ]
