# Generated by Django 5.2.9 on 2025-12-29 06:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AllowedManagerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('memo', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentSchedule',
            fields=[
                ('year', models.PositiveSmallIntegerField(help_text='모집 연도', primary_key=True, serialize=False)),
                ('application_start', models.DateTimeField(help_text='서류 지원 기간 시작')),
                ('application_end', models.DateTimeField(help_text='서류 지원 기간 종료')),
                ('application_result_start', models.DateTimeField(help_text='서류 합격자 발표 시작')),
                ('interview_start', models.DateTimeField(help_text='면접 기간 시작')),
                ('interview_end', models.DateTimeField(help_text='면접 기간 종료')),
                ('interview_result_start', models.DateTimeField(help_text='최종 합격자 발표 시작')),
                ('interview_result_end', models.DateTimeField(help_text='최종 합격자 발표 종료')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='면접 시작 일시 (end와 같은 날)')),
                ('end', models.DateTimeField(help_text='면접 종료 일시 (start와 같은 날)')),
                ('interview_method', models.CharField(choices=[('OFFLINE', '대면'), ('ONLINE', '비대면')], help_text='면접 방식', max_length=7)),
                ('recruitment_schedule', models.ForeignKey(help_text='특정 연도의 모집 일정', on_delete=django.db.models.deletion.CASCADE, related_name='interview_schedules', to='managers.recruitmentschedule')),
            ],
        ),
    ]
