# Generated by Django 5.2.9 on 2025-12-30 06:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('name', models.CharField(help_text='이름', max_length=30)),
                ('phone_number', models.CharField(help_text='전화번호', max_length=13)),
                ('birthday', models.DateField(help_text='생년월일')),
                ('department', models.CharField(help_text='학과', max_length=50)),
                ('student_number', models.CharField(help_text='학번', max_length=7, primary_key=True, serialize=False)),
                ('grade', models.CharField(help_text='학년', max_length=20)),
                ('interview_method', models.CharField(choices=[('OFFLINE', '대면'), ('ONLINE', '비대면')], help_text='면접 참여 방식', max_length=7)),
                ('interview_available_times', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=list, help_text='면접 가능 시간', size=None)),
                ('interview_at', models.DateTimeField(blank=True, help_text='면접 확정 시간', null=True)),
                ('part', models.CharField(choices=[('PM_DESIGN', '기획·디자인'), ('FRONTEND', '프론트엔드'), ('BACKEND', '백엔드')], help_text='지원 파트', max_length=9)),
                ('personal_statement_1', models.CharField(help_text='자기소개 1번 문항의 답변', max_length=500)),
                ('personal_statement_2', models.CharField(help_text='자기소개 2번 문항의 답변', max_length=500)),
                ('personal_statement_3', models.CharField(help_text='자기소개 3번 문항의 답변', max_length=500)),
                ('personal_statement_4', models.CharField(help_text='자기소개 4번 문항의 답변', max_length=500)),
                ('personal_statement_5', models.TextField(help_text='자기소개 5번 문항의 답변')),
                ('completed_prerequisites', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, help_text='선수강 강의 이수 내역', size=3)),
                ('portfolios', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, help_text='포트폴리오', size=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='지원서 추가 일시')),
                ('application_code', models.CharField(help_text='지원 코드', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', '심사중'), ('ACCEPTED', '합격'), ('REJECTED', '불합격')], default='PENDING', help_text='합불 여부', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentSchedule',
            fields=[
                ('year', models.PositiveSmallIntegerField(help_text='모집 연도', primary_key=True, serialize=False)),
                ('application_start', models.DateTimeField(help_text='서류 지원 기간 시작')),
                ('application_end', models.DateTimeField(help_text='서류 지원 기간 종료')),
                ('first_result_start', models.DateTimeField(help_text='1차 합격자 발표 시작')),
                ('interview_start', models.DateTimeField(help_text='면접 기간 시작')),
                ('interview_end', models.DateTimeField(help_text='면접 기간 종료')),
                ('final_result_start', models.DateTimeField(help_text='최종 합격자 발표 시작')),
                ('final_result_end', models.DateTimeField(help_text='최종 합격자 발표 종료')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='면접 시작 일시 (end와 같은 날)')),
                ('end', models.DateTimeField(help_text='면접 종료 일시 (start와 같은 날)')),
                ('interview_method', models.CharField(choices=[('OFFLINE', '대면'), ('ONLINE', '비대면')], help_text='면접 방식', max_length=7)),
                ('recruitment_schedule', models.ForeignKey(help_text='특정 연도의 모집 일정', on_delete=django.db.models.deletion.CASCADE, related_name='interview_schedules', to='recruitments.recruitmentschedule')),
            ],
        ),
    ]
