# Generated by Django 5.2.9 on 2026-01-04 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('max_capacity', models.PositiveSmallIntegerField(default=3)),
                ('interview_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='recruitments.interviewschedule')),
            ],
        ),
    ]
