# Generated by Django 5.2.9 on 2026-01-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentschedule',
            name='interview_end',
            field=models.DateField(blank=True, help_text='면접 기간 종료', null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentschedule',
            name='interview_start',
            field=models.DateField(blank=True, help_text='면접 기간 시작', null=True),
        ),
    ]
