# Generated by Django 5.2.9 on 2026-01-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='completed_prerequisites',
        ),
        migrations.RemoveField(
            model_name='application',
            name='portfolios',
        ),
        migrations.AddField(
            model_name='application',
            name='completed_prerequisite_1',
            field=models.ImageField(blank=True, help_text='선수강 강의 이수 내역', null=True, upload_to='application/completed_prerequisite'),
        ),
        migrations.AddField(
            model_name='application',
            name='completed_prerequisite_2',
            field=models.ImageField(blank=True, help_text='선수강 강의 이수 내역', null=True, upload_to='application/completed_prerequisite'),
        ),
        migrations.AddField(
            model_name='application',
            name='completed_prerequisite_3',
            field=models.ImageField(blank=True, help_text='선수강 강의 이수 내역', null=True, upload_to='application/completed_prerequisite'),
        ),
        migrations.AddField(
            model_name='application',
            name='portfolio_1',
            field=models.FileField(blank=True, help_text='포트폴리오', null=True, upload_to='application/portfolio'),
        ),
        migrations.AddField(
            model_name='application',
            name='portfolio_2',
            field=models.FileField(blank=True, help_text='포트폴리오', null=True, upload_to='application/portfolio'),
        ),
        migrations.AddField(
            model_name='application',
            name='portfolio_3',
            field=models.FileField(blank=True, help_text='포트폴리오', null=True, upload_to='application/portfolio'),
        ),
    ]
