# Generated by Django 5.2.9 on 2026-01-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0002_remove_application_completed_prerequisites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentschedule',
            name='interview_end',
            field=models.DateField(blank=True, help_text='면접 기간 종료', null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentschedule',
            name='interview_start',
            field=models.DateField(blank=True, help_text='면접 기간 시작', null=True),
        ),
    ]
